### ISSUE TITLE
Does not support Keystone Liberty

### ISSUE THREAD

**Issue by spudfkc** [ging/keystone-oauth2-extension#7]
This extension does not work with the latest stable release of Keystone (Liberty).

The issue I've seen to far is that the imports are all wrong as they have been changed.

**Comment by federicofdez** [comment]
Hi @spudfkc, 

This Keystone extension is actually an old version, and unfortunately we haven't planned to develop a stable one within a short-term period. For this reason, you may encounter issues like this one when trying to incorporate it to your Keystone installation.

Anyway, if you manage to fix it, we'll be happy to merge your pull request.

Best regards,

**Comment by federicofdez** [comment]
Closed for inactivity.

BR
